### ISSUE TITLE
Song was privated and later unprivated, now song video page is empty

### ISSUE THREAD

**Issue by cmkeever** [HolodexNet/Musicdex#112]
Nabi broke her songs in Musicdex.  Example:
https://holodex.net/watch/Ae39xRZ0tpA works and plays the song video and still shows the song in the songs section below, and the video is listed on Nabi's channel.
https://music.holodex.net/video/Ae39xRZ0tpA (or click on music note) shows "Stream is not yet tagged with any songs."

This video along with 3 other song videos on her channel were privated a couple months ago and unprivated a week or two ago, so I assume that's what has caused the problem.  FWIW just getting rid of the pruning feature altogether would be a fine solution (hopefully retroactive) as I've seen Musicdex gracefully jump past privated videos on a playlist before.  I didn't tag these originally and haven't tried adding duplicate songs to see if that would clear the problem.

**Comment by P-man2976** [comment]
This problem is caused by the database in Holodex not being updated after the video was unprivated. The issue seems to be resolved when the administrator uses the recrawl command (the example video's song list has been restored). If you find a video in a similar state again, it would be appreciated if you could let us know on the [Discord server](https://discord.gg/NPckPg7EJG) or in an Issue.
